name = "ai-chatbot"
type = "nextjs"
account_id = "fad03f88124cd8f1979d1564faf4c026"
workers_dev = true
compatibility_date = "2023-10-21"

[env.production]
name = "ai-chatbot-prod"
route = "gptmarketplus.org/*"
zone_id = "fab6007826c3bd37437bdc5a8f56b3b9"

# Environment variables (use wrangler secret for sensitive data)
[vars]
# Database configuration (use Turso for production)
POSTGRES_URL = ""
# Redis configuration (set via wrangler secret)
UPSTASH_REDIS_REST_URL = ""
# API keys (set via wrangler secret)
OPENAI_API_KEY = ""
XAI_API_KEY = ""
# Sentry DSN (optional)
SENTRY_DSN = ""
# Auth configuration
NEXTAUTH_URL = "https://gptmarketplus.org"

[triggers]
crons = ["0 0 * * *"] # Daily maintenance task

# Use wrangler secret put <NAME> to set these sensitive variables:
# - UPSTASH_REDIS_REST_TOKEN
# - OPENAI_API_KEY  
# - XAI_API_KEY
# - DATABASE_AUTH_TOKEN
# - AUTH_SECRET
