name = "ai-chatbot"
compatibility_date = "2023-10-21"

[vars]
POSTGRES_URL = "postgresql://postgres:postgres@localhost:5432/aimarket"
UPSTASH_REDIS_REST_URL = "https://well-ringtail-40677.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "AZ7lAAIjcDE2ZjliN2RmNWNlNWQ0YTg5YWIyYmJjMjg1YjU0OTE0Y3AxMA"
# SENTRY_DSN is left empty; provide a valid DSN or remove this line if not using Sentry
SENTRY_DSN = ""


[triggers]
crons = ["0 0 * * *"] # Example: daily scheduled task
